### ISSUE TITLE
Bluetooth mesurements, use always phone time alwais

### ISSUE THREAD

**Issue by angeld-jr2** [derdilla/blood-pressure-monitor-fl#450] opened 2024-09-25 11:09 UTC
### What you want:

if the bluetooth device time is incorrect, import measurament time too. 

A option to force always phone time to bypass bad time is a nicely option.

### Why you want it:

Bad time mesuraments are invalid in all cases.

Thanks.

**Comment by derdilla** [comment] 2024-09-25 11:34
Yes, that should really be fixed. Closing this as duplicate of #410, feel free to reopen if you think differently.

**Closed by derdilla** 2024-09-25 11:34 UTC
Labels: enhancement
